#!/bin/bash
# get admin privileges
sudo su
# install httpd 
yum update -y
yum install -y httpd.x86_64
systemctl start httpd.service
systemctl enable httpd.service
echo "Hello from server one " > /var/www/html/index.html
